# Site wide configuration

title: Matthew Lab
description: "Matthew Owen Moreira's personal website"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: https://MatthewOM.github.io/MatthewOM/

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist


# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: article
page_layout: article

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Matthew Owen Moreira
  email: matthew.moreira@ua.pt
  bio: "PhD"
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus: 
  disqus-shortname: MatthewOM


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]

google_verify: LG_KnLguQHN2dFnje86YgIzOrPVdEH_jmdRIfJLIXrw
google_analytics: UA-141115051-1

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap


